name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-pypi:
    name: Release (PyPI)
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Build Distribution(s)
        run: uv build --wheel
      - name: Publish Distribution(s)
        run: uv publish
